### ISSUE TITLE
In projects list, when no logo is present, instead of some nice text, a "missing image" is displayed

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/chips-alliance-website#47]
We initially input no logo for the FPGA tool perf and that is what happened:

![Screenshot from 2023-03-30 17-24-50](https://user-images.githubusercontent.com/140166/228885884-3486eea9-8dfb-4cbf-9b3a-b2e615419c83.png)

Obviously the behavior should be different - there should just be no logo, or a placeholder of some sort.

**Comment by cjyabraham** [comment]
For now, what about creating a greyed out version of the chip in the CHIPS logo? That should be obvious to people that it is just a placeholder. Like this but grey:
<img width="163" alt="Screen Shot 2023-03-31 at 5 15 29 PM" src="https://user-images.githubusercontent.com/463160/229093526-67ff1636-d37b-47e9-9fd6-0e5120a843fe.png">

**Comment by mgielda** [comment]
awesome! can you just use a negative of this, when you create the mechanism, we can replace it in the repo later.

**Comment by mgielda** [comment]
(I don't want the drawing of this to be a blocker, we'll get it done sometime next week and just replace it)

**Comment by cjyabraham** [comment]
I've [created the placeholder logo here](https://github.com/chipsalliance/chips-alliance-website/commit/8bc7ccaa0d955e1b8eacba7fef5d3ff83008f409). It does not seem that the [hugo `fileExists` function](https://gohugo.io/functions/fileexists/) works in this situation since we are pulling the logo files in via hugo modules. I tested it out and it will only detect existence of files local to the website repo. As a workaround we could copy the placeholder logo into [the tsc project images directory](https://github.com/chipsalliance/tsc/tree/main/projects/logos) with filename of the project's missing logo. Would that be acceptable?

**Comment by mgielda** [comment]
Hi @cjyabraham, no, we are actually pulling the TSC logos in during build via git clone now (my colleagues replaced hugo modules with this, so that we don't have to update anything every time we change the TSC repo). Now the build just takes the tip of https://github.com/chipsalliance/tsc main branch. Meaning fileExists should probably work. Please make sure that when implementing this you start from the current main of this repo with the changes my team made.

**Comment by cjyabraham** [comment]
Ah, you're right. Ok, I've checked in a change which will do this and show the placeholder logo when the project logo doesn't exist, like this:
<img width="1063" alt="Screen Shot 2023-04-04 at 12 51 27 PM" src="https://user-images.githubusercontent.com/463160/229699832-f7cc4153-b886-4f53-9feb-56e46113c402.png">
